In [1]:
import pandas as pd
import numpy as np

### 1. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [41]:
# N is the number of columns in the output. If N is not specified, a square array is returned (N = len(x)).
def Vandermonde(vector, N=0, increasing=False):
    if N==0:
        N=len(vector)
    if increasing==False:
        matrix= np.column_stack([(vector)**(N-i-1) for i in range(N)])
    else:
        matrix= np.column_stack([(vector)**(i) for i in range(N)])
    return matrix


In [42]:
x=np.array([1,2,4,6])
Vandermonde(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   4,  16,  64],
       [  1,   6,  36, 216]])

In [56]:
Vandermonde(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]])

### 2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [53]:
def MA(sequens, k):
    output=[]
    for i in range(len(sequens)-k+1):
        y=np.mean(sequens[i:i+k])
        output.append(y)
    return np.round(output, decimals=2)

In [54]:
z=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
MA(z,4)

array([25., 35., 45., 55., 65., 75., 85.])

In [55]:
z=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
MA(z,3)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])